### ISSUE TITLE
Dracula theme doesn't show correct colors

### ISSUE THREAD

**Issue by filipemacedo** [dracula/visual-studio-code#155]
![image](https://user-images.githubusercontent.com/28747696/82422105-66c1d500-9a58-11ea-9d14-9a42bf84c8fb.png)

Hello, my theme doesn't show the correct colors of the variables. When I open vscode, it shows the correct colors for a few seconds, but then changes to that color.

My vscode config (except theme color): https://gist.github.com/diego3g/b1b189063d21b96d6144ca896755be64

Can you help me?

**Comment by dsifford** [comment]
This is because of semantic highlighting. The "const" variables are treated as true constants by the semantic highlighter, which is why they are purple.

There was talk that someone was going to look into this specifically for js/ts, but not sure when this will actually happen.

For now, you can disable semantic highlighting in your editor by disabling semantic highlighting in your user settings.
