### ISSUE TITLE
Adjust `editor.selectionBackground` & `editor.selectionHighlightBackground`

### ISSUE THREAD

**Issue by wenfangdu** [dracula/visual-studio-code#183]
Currently, these two colors are almost indistinguishable, more contrast would be better.

![image](https://user-images.githubusercontent.com/28700378/124348906-39fe5c00-dc1f-11eb-891f-d352f0ad5ab8.png)

Can't tell `statusBar` with the cursor is selected or not:

![image](https://user-images.githubusercontent.com/28700378/124348812-cfe5b700-dc1e-11eb-8d5e-12090e323a74.png)

**Comment by dsifford** [comment]
I tried playing with this for a bit just now and it's unfortunately not as simple as just adjusting those two regions.

This gets tricky, particular in "smarter" synataxes (like javascript, for example) because `editor.wordHighlightBackground` and `editor.wordHighlightStrongBackground` seem to also play a role in this and that role appears to be of a higher priority.

So I'm not sure there is an easy fix. Feel free to propose a solution if you have one.

**Comment by wenfangdu** [comment]
@dsifford Fixing https://github.com/dracula/visual-studio-code/issues/184 would partially solve this issue.

As for

> This gets tricky, particularly in "smarter" syntaxes (like javascript, for example) because `editor.wordHighlightBackground` and `editor.wordHighlightStrongBackground` seem to also play a role in this and that role appears to be of a higher priority.

We can fix this later if a better solution is raised.

**Comment by wenfangdu** [comment]
@dsifford @luxonauta @zenorocha Please reopen this issue, since #253 has been reverted.
