### ISSUE TITLE
Radio buttons look confusing 

### ISSUE THREAD

**Issue by vanmash** [dracula/visual-studio-code#197]
Radio buttons look confusing in Jira and Bitbucket (Atlassian Labs) v2.9.1 extension.
`on` button is grey and `off` is white.

For comparison GitHub Theme v4.1.1

Could you take a look?

Dracula Official v2.24.0
![on1](https://user-images.githubusercontent.com/2527832/132315383-2650d8cd-7fe4-4ca2-96f3-a5c00a0d0db9.PNG)
![off1](https://user-images.githubusercontent.com/2527832/132315359-5ee283c2-b0f0-4222-9328-f70286c9772e.PNG)

GitHub Theme v4.1.1 (for comparison)

![on2a](https://user-images.githubusercontent.com/2527832/132315300-6a84fdf5-d59e-48b2-9b38-6cf89d0ed890.PNG)
![off2a](https://user-images.githubusercontent.com/2527832/132315269-d86d164a-0921-43d5-ac2b-0bebf7cd3e9f.PNG)

**Comment by Delapouite** [comment]
I agree that these radio buttons are disturbing. It feels like they are "inverted", because when they are on, they are dimmed.

By inspecting how they are rendered with VSCode (Ctrl+Shift+I), it appears that the current "checked color is : 

```css
MuiSwitch-colorPrimary.Mui-checked {
    color: #44475a;
}
```

Don't know yet what is the correct way to fix this, but I'll try to come up with something.
