### ISSUE TITLE
Theme improvements

### ISSUE THREAD

**Issue by ajitid** [dracula/visual-studio-code#40]
Can you make Dracula theme more minimal by making just one change &mdash; "activityBar.background": "#21222C" ?

![capture](https://cloud.githubusercontent.com/assets/26769888/26249865/bddde8f4-3cc5-11e7-934a-760284615ab2.PNG)

**Comment by ajitid** [comment]
![screenshot 212](https://cloud.githubusercontent.com/assets/26769888/26278073/fc134aec-3db0-11e7-83e9-3a3c563bfa82.png)

Can't this intellisense suggestion be colored?

**Comment by ajitid** [comment]
https://github.com/Microsoft/vscode/issues/25966
Ability to change color of selection of fields like find and replace
Please add this one once this customisation becomes available.

**Comment by ajitid** [comment]
Don't want to add up your work

**Comment by dsifford** [comment]
@ajitid Hey, sorry for the radio silence! Went on vacation last weekend and forgot about this.

I'm actually working on getting #12 finished tonight and tomorrow so I'll be able to address the things you brought up.

### To comment on them individually:

#### Activity bar background

I actually sort of like it where it is and the feedback I received when I initially made the change all sounded like they liked it too. So I'm gonna keep as-is for now.

#### Intellisense

That should be colored automatically. Not sure why it isn't. Might want to ask the vscode people about that since they maintain the C, C++, C#, etc tmLanguages.

#### Selection color

Yes, I'll definitely change when it hits the stable build

> "Don't want to add up your work"

Please do! I ❤️ feedback.

**Comment by ajitid** [comment]
Okay, for intellisense you'll need to add a new property
https://github.com/Microsoft/vscode/issues/26671

**Comment by dsifford** [comment]
@ajitid Awesome, that's a huge help. Thanks!

**Comment by dsifford** [comment]
@ajitid Closing this in favor of #41 ... Put anything else related to the May stable release there. 👍
