### ISSUE TITLE
Wrong colors for git and built-in terminal

### ISSUE THREAD

**Issue by hacknug** [dracula/visual-studio-code#70]
I've just installed the theme on VSCode and the colors used for the git status of edited files and the built-in terminal don't use the Dracula color scheme.

Is this because of any limitations? Are you guys opened for a PR that fixes this?

<img width="417" alt="captura de pantalla 2018-03-26 a las 16 08 48" src="https://user-images.githubusercontent.com/1107521/37911313-fedd775e-310f-11e8-83c3-3170d48db85f.png">
<img width="228" alt="captura de pantalla 2018-03-26 a las 16 08 43" src="https://user-images.githubusercontent.com/1107521/37911314-fefb42a2-310f-11e8-8509-71a6b01d136e.png">

**Comment by dsifford** [comment]
Hi,

The terminal colors were adjusted due to some limitations that resulted with the colors required for ANSI. You can find the details of that discussion in #66

The git modified color (the orange color), is a part of the [Dracula palette](https://github.com/dracula/dracula-theme#color-palette). Was there some other color you expected?
